### PR TITLE
Add info about MagpieOS

### PR DESCRIPTION
**Pull request by mominul**
"OpenBangla Keyboard is the default Bangla writing software for [MagpieOS](http://www.magpieos.net), the first Bangladeshi Linux distribution."

cc @Rizwan-Hasan

### CODE REVIEW

**Comment by bdeshi** [comment]
Definitely not the first Bangladeshi distro. Please change that to something like "a popular/new/fresh" etc.

**Comment by mominul** [comment]
@bdeshi  Thanks for the info! Afterward, @Rizwan-Hasan also informed me of this fact. He said that MagpieOS is the first Arch Linux based Bangladeshi distro.

So will I change it to "... MagpieOS, a Bangladeshi Linux distribution." or give it the credit of being the first Arch based Bangladeshi distribution? Any thoughts? :laughing:

**Comment by bdeshi** [comment]
sure, sounds good!

**Comment by Rizwan-Hasan** [comment]
☺

**Pull request merged**
