### PR TITLE
Introduce Systray entry for TopBar

### LINKED ISSUE #151: Should be displayed on GNOME topbar

### PR DESCRIPTION
**Pull request by mominul**
This PR introduces a systray entry implementation for OpenBangla Keyboard TopBar. This will be an alternative approach for the user to configure OBK through the Systray entry while keeping the TopBar hidden.

OBK Systray

Currently, the available options have been kept minimal and more options will be added based on user experiences. But of course, I'd like to hear suggestions!

resolves  #151.

### CODE REVIEW

**Comment by mominul** [comment]
cc @Adyel @bdeshi @ahmubashshir

**Comment by Adyel** [comment]
> This PR introduces a systray entry implementation for OpenBangla Keyboard TopBar. This will be an alternative approach for the user to configure OBK through the Systray entry while keeping the TopBar hidden.

Looks fantastic 👍🏽

**Comment by mominul** [comment]
Unfortunately, it's not customizable. Even the Gnome DE doesn't support Systray natively because of their controversial decision to remove this feature entirely. Applications that need Systray support require a gnome extension to be installed.
elementaryOS has also removed this feature without giving any alternatives. That's one of the reasons I can't make this default and remove the TopBar thing entirely. :disappointed:

**Comment by gunnarhj** [comment]
As regards GNOME, if an IBus input method is selected, it typically shows some options — including an option to open the preferences/setup window — via the input source indicator. Example:

example-input-source-indicator

Will this change make OpenBangla Keyboard work in a similar way on GNOME?

**Comment by mominul** [comment]
> Will this change make OpenBangla Keyboard work in a similar way on GNOME?

Actually, no. This PR introduces a Systray entry through the `openbangla-gui` user-facing application. It's a completely separate application from the OpenBangla ibus engine and uses the Qt framework for the UI.

On the other hand, the Chinese Pinyin engine uses the IBus API to create the options in the Input Source Indicator. I intend to check out the API in the future.

**Pull request merged**
