### PR TITLE
Install script

### PR DESCRIPTION
**Pull request by Adyel**
Final Merge to the main branch. Need to Fix some conflict which occurred due to directly editing main branch.

### CODE REVIEW

**Comment by mominul** [comment]
I think you should create a new branch from master and add the patch on that branch instead. If we resolve the conflicts(rebase) and merge it, it'd cause some history conflict. So please open a new branch. :)

**Comment by Adyel** [comment]
@mominul  We got conflict in a single file. This will be easy to fix. I can not do that because I don't have access. Can you please download [Gitkraken](https://www.gitkraken.com/)  It will make everything easier  (for now and future).

**Comment by mominul** [comment]
@Adyel  If you don't mind, can I open a new PR with your patch?

**Comment by Adyel** [comment]
@mominul  Go ahead. :+1:

**Pull request closed without merging**
